import { Vector } from "../utils-ts/modules/geometry/Vector.mjs";
import { Grid } from "../utils-ts/modules/Grid.mjs";
import { Room } from "./Room.mjs";
import { Gate } from "./tiles/Gate.mjs";

export const ROOMS: Room[] = [
	new Room(
		"two-wide-platforms",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 3, y: 8, type: "solid" },
			{ x: 4, y: 8, type: "solid" },
			{ x: 5, y: 8, type: "solid" },
			{ x: 6, y: 8, type: "solid" },
			{ x: 7, y: 8, type: "solid" },
			{ x: 8, y: 8, type: "solid" },
			{ x: 3, y: 3, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 5, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 8, y: 3, type: "solid" },
			{ x: 10, y: 1, type: "solid" },
			{ x: 1, y: 1, type: "solid" },
			{ x: 1, y: 10, type: "solid" },
			{ x: 10, y: 10, type: "solid" },
		],
		[
			{ x: 6, y: 0, direction: "up" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 3, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
			{ x: 8, y: 0, direction: "up" },
			{ x: 11, y: 3, direction: "right" },
			{ x: 11, y: 4, direction: "right" },
			{ x: 11, y: 5, direction: "right" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 8, y: 11, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 3, y: 11, direction: "down" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 3, direction: "left" },
		],
		[],
		["left", "right", "up", "down"]
	),
	new Room(
		"empty-room",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 1, y: 9, type: "solid" },
			{ x: 1, y: 10, type: "solid" },
			{ x: 2, y: 10, type: "solid" },
			{ x: 3, y: 10, type: "solid" },
			{ x: 4, y: 10, type: "solid" },
			{ x: 5, y: 10, type: "solid" },
			{ x: 6, y: 10, type: "solid" },
			{ x: 7, y: 10, type: "solid" },
			{ x: 8, y: 10, type: "solid" },
			{ x: 9, y: 10, type: "solid" },
			{ x: 10, y: 10, type: "solid" },
			{ x: 10, y: 9, type: "solid" },
			{ x: 3, y: 11, type: "solid" },
			{ x: 4, y: 11, type: "solid" },
			{ x: 8, y: 11, type: "solid" },
			{ x: 7, y: 11, type: "solid" },
			{ x: 6, y: 11, type: "solid" },
			{ x: 5, y: 11, type: "solid" },
			{ x: 3, y: 0, type: "solid" },
			{ x: 4, y: 0, type: "solid" },
			{ x: 5, y: 0, type: "solid" },
			{ x: 6, y: 0, type: "solid" },
			{ x: 7, y: 0, type: "solid" },
			{ x: 8, y: 0, type: "solid" },
			{ x: 1, y: 1, type: "solid" },
			{ x: 10, y: 1, type: "solid" },
			{ x: 9, y: 9, type: "solid" },
			{ x: 2, y: 9, type: "solid" },
			{ x: 4, y: 1, type: "solid" },
			{ x: 5, y: 1, type: "solid" },
			{ x: 6, y: 1, type: "solid" },
			{ x: 7, y: 1, type: "solid" },
			{ x: 5, y: 2, type: "solid" },
			{ x: 6, y: 2, type: "solid" },
		],
		[
			{ x: 11, y: 5, direction: "right" },
			{ x: 11, y: 4, direction: "right" },
			{ x: 11, y: 3, direction: "right" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 0, y: 3, direction: "left" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 8, direction: "left" },
		],
		[],
		["left", "right"]
	),
	new Room(
		"platform-over-pit",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 1, y: 9, type: "solid" },
			{ x: 1, y: 10, type: "solid" },
			{ x: 2, y: 10, type: "solid" },
			{ x: 9, y: 10, type: "solid" },
			{ x: 10, y: 10, type: "solid" },
			{ x: 10, y: 9, type: "solid" },
			{ x: 9, y: 9, type: "solid" },
			{ x: 2, y: 9, type: "solid" },
			{ x: 11, y: 3, type: "solid" },
			{ x: 10, y: 2, type: "solid" },
			{ x: 9, y: 2, type: "solid" },
			{ x: 2, y: 2, type: "solid" },
			{ x: 0, y: 3, type: "solid" },
			{ x: 1, y: 2, type: "solid" },
			{ x: 1, y: 1, type: "solid" },
			{ x: 2, y: 1, type: "solid" },
			{ x: 9, y: 1, type: "solid" },
			{ x: 10, y: 1, type: "solid" },
			{ x: 3, y: 6, type: "platform" },
			{ x: 4, y: 6, type: "platform" },
			{ x: 5, y: 6, type: "platform" },
			{ x: 6, y: 6, type: "platform" },
			{ x: 7, y: 6, type: "platform" },
			{ x: 8, y: 6, type: "platform" },
			{ x: 9, y: 6, type: "solid" },
			{ x: 2, y: 6, type: "solid" },
			{ x: 10, y: 3, type: "solid" },
			{ x: 1, y: 3, type: "solid" },
			{ x: 9, y: 3, type: "solid" },
			{ x: 2, y: 3, type: "solid" },
			{ x: 8, y: 11, type: "platform" },
			{ x: 7, y: 11, type: "platform" },
			{ x: 8, y: 0, type: "solid" },
			{ x: 8, y: 1, type: "solid" },
			{ x: 8, y: 2, type: "solid" },
			{ x: 3, y: 3, type: "solid" },
			{ x: 3, y: 2, type: "solid" },
			{ x: 3, y: 1, type: "solid" },
			{ x: 3, y: 0, type: "solid" },
			{ x: 4, y: 3, type: "platform" },
			{ x: 5, y: 3, type: "platform" },
			{ x: 3, y: 9, type: "solid" },
			{ x: 6, y: 11, type: "platform" },
		],
		[
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 11, y: 5, direction: "right" },
			{ x: 11, y: 4, direction: "right" },
			{ x: 3, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 8, y: 11, direction: "down" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 6, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
			{ x: 7, y: 1, direction: "up" },
			{ x: 6, y: 1, direction: "up" },
			{ x: 5, y: 1, direction: "up" },
			{ x: 4, y: 1, direction: "up" },
			{ x: 5, y: 2, direction: "up" },
			{ x: 6, y: 2, direction: "up" },
			{ x: 7, y: 2, direction: "up" },
			{ x: 6, y: 3, direction: "up" },
			{ x: 4, y: 2, direction: "up" },
			{ x: 4, y: 3, direction: "up" },
			{ x: 5, y: 3, direction: "up" },
			{ x: 7, y: 3, direction: "up" },
			{ x: 8, y: 3, direction: "up" },
		],
		["down"],
		["left", "right"]
	),
	new Room(
		"vertical-chute",[
			{ x: 0, y: 0, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 3, y: 8, type: "platform" },
			{ x: 4, y: 8, type: "platform" },
			{ x: 5, y: 8, type: "platform" },
			{ x: 8, y: 5, type: "platform" },
			{ x: 7, y: 5, type: "platform" },
			{ x: 6, y: 5, type: "platform" },
			{ x: 3, y: 2, type: "platform" },
			{ x: 4, y: 2, type: "platform" },
			{ x: 5, y: 2, type: "platform" },
			{ x: 9, y: 10, type: "solid" },
			{ x: 9, y: 9, type: "solid" },
			{ x: 9, y: 8, type: "solid" },
			{ x: 10, y: 8, type: "solid" },
			{ x: 10, y: 7, type: "solid" },
			{ x: 10, y: 6, type: "solid" },
			{ x: 10, y: 5, type: "solid" },
			{ x: 9, y: 5, type: "solid" },
			{ x: 9, y: 4, type: "solid" },
			{ x: 9, y: 3, type: "solid" },
			{ x: 9, y: 2, type: "solid" },
			{ x: 9, y: 1, type: "solid" },
			{ x: 10, y: 2, type: "solid" },
			{ x: 10, y: 3, type: "solid" },
			{ x: 10, y: 1, type: "solid" },
			{ x: 10, y: 4, type: "solid" },
			{ x: 11, y: 4, type: "solid" },
			{ x: 11, y: 3, type: "solid" },
			{ x: 11, y: 5, type: "solid" },
			{ x: 11, y: 6, type: "solid" },
			{ x: 11, y: 7, type: "solid" },
			{ x: 11, y: 8, type: "solid" },
			{ x: 10, y: 9, type: "solid" },
			{ x: 10, y: 10, type: "solid" },
			{ x: 9, y: 7, type: "solid" },
			{ x: 9, y: 6, type: "solid" },
			{ x: 0, y: 3, type: "solid" },
			{ x: 0, y: 8, type: "solid" },
			{ x: 1, y: 1, type: "solid" },
			{ x: 1, y: 2, type: "solid" },
			{ x: 1, y: 3, type: "solid" },
			{ x: 1, y: 8, type: "solid" },
			{ x: 1, y: 9, type: "solid" },
			{ x: 1, y: 10, type: "solid" },
			{ x: 2, y: 10, type: "solid" },
			{ x: 2, y: 9, type: "solid" },
			{ x: 2, y: 8, type: "solid" },
			{ x: 2, y: 3, type: "solid" },
			{ x: 2, y: 2, type: "solid" },
			{ x: 2, y: 1, type: "solid" },
			{ x: 2, y: 4, type: "solid" },
			{ x: 1, y: 4, type: "solid" },
			{ x: 0, y: 4, type: "solid" },
			{ x: 8, y: 11, type: "platform" },
			{ x: 7, y: 11, type: "platform" },
			{ x: 6, y: 11, type: "platform" },
		],
		[
			{ x: 8, y: 11, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 3, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 8, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
			{ x: 6, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 3, y: 0, direction: "up" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 1, y: 5, direction: "left" },
			{ x: 1, y: 6, direction: "left" },
			{ x: 1, y: 7, direction: "left" },
			{ x: 2, y: 7, direction: "left" },
			{ x: 2, y: 6, direction: "left" },
			{ x: 2, y: 5, direction: "left" },
			{ x: 5, y: 11, direction: "down" },
		],
		["up", "down"],
		["left"]
	),
	new Room(
		"hallway-gates", [
			{ x: 0, y: 0, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 1, y: 9, type: "solid" },
			{ x: 1, y: 10, type: "solid" },
			{ x: 2, y: 10, type: "solid" },
			{ x: 3, y: 10, type: "solid" },
			{ x: 4, y: 10, type: "solid" },
			{ x: 5, y: 10, type: "solid" },
			{ x: 6, y: 10, type: "solid" },
			{ x: 7, y: 10, type: "solid" },
			{ x: 8, y: 10, type: "solid" },
			{ x: 9, y: 10, type: "solid" },
			{ x: 10, y: 10, type: "solid" },
			{ x: 10, y: 9, type: "solid" },
			{ x: 9, y: 9, type: "solid" },
			{ x: 8, y: 9, type: "solid" },
			{ x: 7, y: 9, type: "solid" },
			{ x: 6, y: 9, type: "solid" },
			{ x: 5, y: 9, type: "solid" },
			{ x: 4, y: 9, type: "solid" },
			{ x: 3, y: 9, type: "solid" },
			{ x: 2, y: 9, type: "solid" },
			{ x: 3, y: 11, type: "solid" },
			{ x: 4, y: 11, type: "solid" },
			{ x: 8, y: 11, type: "solid" },
			{ x: 7, y: 11, type: "solid" },
			{ x: 6, y: 11, type: "solid" },
			{ x: 5, y: 11, type: "solid" },
			{ x: 3, y: 0, type: "solid" },
			{ x: 4, y: 0, type: "solid" },
			{ x: 5, y: 0, type: "solid" },
			{ x: 6, y: 0, type: "solid" },
			{ x: 7, y: 0, type: "solid" },
			{ x: 8, y: 0, type: "solid" },
			{ x: 10, y: 2, type: "solid" },
			{ x: 9, y: 2, type: "solid" },
			{ x: 8, y: 2, type: "solid" },
			{ x: 7, y: 2, type: "solid" },
			{ x: 6, y: 2, type: "solid" },
			{ x: 5, y: 1, type: "solid" },
			{ x: 4, y: 1, type: "solid" },
			{ x: 3, y: 1, type: "solid" },
			{ x: 2, y: 1, type: "solid" },
			{ x: 1, y: 1, type: "solid" },
			{ x: 1, y: 2, type: "solid" },
			{ x: 3, y: 2, type: "solid" },
			{ x: 4, y: 2, type: "solid" },
			{ x: 6, y: 1, type: "solid" },
			{ x: 7, y: 1, type: "solid" },
			{ x: 8, y: 1, type: "solid" },
			{ x: 9, y: 1, type: "solid" },
			{ x: 10, y: 1, type: "solid" },
			{ x: 2, y: 2, type: "solid" },
			{ x: 5, y: 2, type: "solid" },
			{ x: 8, y: 6, type: "solid" },
			{ x: 7, y: 6, type: "solid" },
			{ x: 6, y: 6, type: "solid" },
			{ x: 5, y: 6, type: "solid" },
			{ x: 4, y: 6, type: "solid" },
			{ x: 3, y: 6, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 5, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 6, y: 4, type: new Gate("down", false) },
			{ x: 6, y: 5, type: new Gate("up", false) },
			{ x: 5, y: 7, type: new Gate("down", true) },
			{ x: 5, y: 8, type: new Gate("up", true) },
		],
		[
			{ x: 11, y: 5, direction: "right" },
			{ x: 11, y: 4, direction: "right" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 0, y: 3, direction: "left" },
			{ x: 11, y: 3, direction: "right" },
		],
		["left", "right"],
		[]
	),
	new Room(
		"tunnels", 
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 3, y: 8, type: "solid" },
			{ x: 4, y: 8, type: "solid" },
			{ x: 5, y: 8, type: "solid" },
			{ x: 6, y: 8, type: "solid" },
			{ x: 7, y: 8, type: "solid" },
			{ x: 8, y: 8, type: "solid" },
			{ x: 3, y: 3, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 5, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 8, y: 3, type: "solid" },
			{ x: 4, y: 4, type: "solid" },
			{ x: 4, y: 5, type: "solid" },
			{ x: 7, y: 7, type: "solid" },
			{ x: 7, y: 6, type: "solid" },
			{ x: 3, y: 11, type: "solid" },
			{ x: 8, y: 11, type: "solid" },
			{ x: 8, y: 0, type: "solid" },
			{ x: 3, y: 0, type: "solid" },
		],
		[
			{ x: 11, y: 3, direction: "right" },
			{ x: 11, y: 4, direction: "right" },
			{ x: 11, y: 5, direction: "right" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 3, direction: "left" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 6, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
		],
		[],
		["left", "right"]
	),
	new Room(
		"tunnels-2", 
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 3, y: 8, type: "solid" },
			{ x: 4, y: 8, type: "solid" },
			{ x: 5, y: 8, type: "solid" },
			{ x: 6, y: 8, type: "solid" },
			{ x: 7, y: 8, type: "solid" },
			{ x: 8, y: 8, type: "solid" },
			{ x: 3, y: 3, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 4, y: 4, type: "solid" },
			{ x: 4, y: 5, type: "solid" },
			{ x: 7, y: 7, type: "solid" },
			{ x: 7, y: 6, type: "solid" },
			{ x: 8, y: 9, type: "solid" },
			{ x: 8, y: 7, type: "solid" },
			{ x: 8, y: 6, type: "solid" },
			{ x: 6, y: 6, type: "platform" },
			{ x: 8, y: 3, type: "solid" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 5, y: 3, type: "solid" },
			{ x: 9, y: 9, type: "platform" },
			{ x: 10, y: 9, type: "platform" },
			{ x: 4, y: 6, type: "solid" },
			{ x: 5, y: 6, type: "platform" },
		],
		[
			{ x: 11, y: 3, direction: "right" },
			{ x: 11, y: 4, direction: "right" },
			{ x: 11, y: 5, direction: "right" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 3, direction: "left" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 6, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
			{ x: 8, y: 0, direction: "up" },
			{ x: 3, y: 0, direction: "up" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 3, y: 11, direction: "down" },
			{ x: 8, y: 11, direction: "down" },
		],
		[],
		["left", "right", "up", "down"]
	),
	new Room(
		"tunnels-and-gates",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 3, y: 8, type: "solid" },
			{ x: 4, y: 8, type: "solid" },
			{ x: 5, y: 8, type: "solid" },
			{ x: 6, y: 8, type: "solid" },
			{ x: 7, y: 8, type: "solid" },
			{ x: 8, y: 8, type: "solid" },
			{ x: 3, y: 3, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 5, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 8, y: 3, type: "solid" },
			{ x: 4, y: 4, type: "solid" },
			{ x: 4, y: 5, type: "solid" },
			{ x: 7, y: 7, type: "solid" },
			{ x: 7, y: 6, type: "solid" },
			{ x: 3, y: 11, type: "solid" },
			{ x: 4, y: 11, type: "solid" },
			{ x: 5, y: 11, type: "solid" },
			{ x: 6, y: 11, type: "solid" },
			{ x: 7, y: 11, type: "solid" },
			{ x: 8, y: 11, type: "solid" },
			{ x: 8, y: 0, type: "solid" },
			{ x: 7, y: 0, type: "solid" },
			{ x: 6, y: 0, type: "solid" },
			{ x: 5, y: 0, type: "solid" },
			{ x: 4, y: 0, type: "solid" },
			{ x: 3, y: 0, type: "solid" },
			{ x: 7, y: 5, type: "solid" },
			{ x: 4, y: 6, type: "solid" },
			{ x: 4, y: 2, type: new Gate("up", true) },
			{ x: 4, y: 1, type: new Gate("down", true) },
			{ x: 7, y: 9, type: new Gate("down", false) },
			{ x: 7, y: 10, type: new Gate("up", false) },
			{ x: 4, y: 7, type: new Gate("down", false) },
			{ x: 7, y: 4, type: new Gate("down", true) },
		],
		[
			{ x: 11, y: 3, direction: "right" },
			{ x: 11, y: 4, direction: "right" },
			{ x: 11, y: 5, direction: "right" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 3, direction: "left" },
		],
		[],
		["left", "right"]
	),
	new Room(
		"vertical-gate-contraption",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 0, y: 8, type: "solid" },
			{ x: 0, y: 6, type: "solid" },
			{ x: 0, y: 5, type: "solid" },
			{ x: 0, y: 4, type: "solid" },
			{ x: 0, y: 3, type: "solid" },
			{ x: 0, y: 7, type: "solid" },
			{ x: 11, y: 3, type: "solid" },
			{ x: 11, y: 4, type: "solid" },
			{ x: 11, y: 5, type: "solid" },
			{ x: 3, y: 0, type: "solid" },
			{ x: 8, y: 0, type: "solid" },
			{ x: 3, y: 11, type: "solid" },
			{ x: 8, y: 11, type: "solid" },
			{ x: 3, y: 7, type: "solid" },
			{ x: 3, y: 6, type: "solid" },
			{ x: 3, y: 5, type: "solid" },
			{ x: 8, y: 3, type: "solid" },
			{ x: 8, y: 6, type: "solid" },
			{ x: 8, y: 7, type: "solid" },
			{ x: 7, y: 11, type: "platform" },
			{ x: 4, y: 11, type: "platform" },
			{ x: 9, y: 6, type: "platform" },
			{ x: 10, y: 6, type: "platform" },
			{ x: 3, y: 4, type: "solid" },
			{ x: 3, y: 3, type: "solid" },
			{ x: 1, y: 4, type: new Gate("right", true) },
			{ x: 2, y: 4, type: new Gate("left", true) },
			{ x: 1, y: 7, type: new Gate("right", false) },
			{ x: 2, y: 7, type: new Gate("left", false) },
			{ x: 4, y: 7, type: "solid" },
			{ x: 5, y: 7, type: "solid" },
			{ x: 6, y: 7, type: "solid" },
			{ x: 7, y: 7, type: "solid" },
			{ x: 11, y: 6, type: "solid" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 7, y: 6, type: "solid" },
			{ x: 7, y: 4, type: new Gate("down", false) },
			{ x: 7, y: 5, type: new Gate("up", false) },
			{ x: 6, y: 6, type: "solid" },
			{ x: 4, y: 3, type: "platform" },
			{ x: 5, y: 3, type: "platform" },
			{ x: 3, y: 8, type: "solid" },
			{ x: 8, y: 8, type: "solid" },
		],
		[
			{ x: 6, y: 0, direction: "up" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
		],
		["up", "down"],
		["right"]
	),
	new Room(
		"the-maze",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 4, y: 8, type: "solid" },
			{ x: 5, y: 8, type: "solid" },
			{ x: 6, y: 8, type: "solid" },
			{ x: 7, y: 8, type: "solid" },
			{ x: 8, y: 8, type: "solid" },
			{ x: 3, y: 3, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 5, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 8, y: 3, type: "solid" },
			{ x: 10, y: 2, type: "solid" },
			{ x: 10, y: 1, type: "solid" },
			{ x: 9, y: 3, type: "solid" },
			{ x: 10, y: 3, type: "solid" },
			{ x: 11, y: 3, type: "solid" },
			{ x: 11, y: 4, type: "solid" },
			{ x: 3, y: 4, type: "solid" },
			{ x: 3, y: 5, type: "solid" },
			{ x: 5, y: 7, type: "solid" },
			{ x: 5, y: 6, type: "solid" },
			{ x: 7, y: 5, type: "solid" },
			{ x: 7, y: 4, type: "solid" },
			{ x: 9, y: 8, type: "solid" },
			{ x: 9, y: 7, type: "solid" },
			{ x: 9, y: 6, type: "solid" },
			{ x: 9, y: 9, type: "solid" },
			{ x: 10, y: 9, type: "platform" },
			{ x: 7, y: 6, type: "solid" },
			{ x: 4, y: 4, type: "solid" },
			{ x: 5, y: 4, type: "solid" },
			{ x: 6, y: 4, type: "solid" },
			{ x: 8, y: 4, type: "solid" },
			{ x: 9, y: 4, type: "solid" },
			{ x: 10, y: 4, type: "solid" },
			{ x: 8, y: 9, type: "solid" },
			{ x: 7, y: 9, type: "solid" },
			{ x: 6, y: 9, type: "solid" },
			{ x: 5, y: 9, type: "solid" },
			{ x: 4, y: 9, type: "solid" },
			{ x: 3, y: 8, type: "platform" },
			{ x: 2, y: 8, type: "platform" },
			{ x: 9, y: 2, type: "solid" },
			{ x: 9, y: 1, type: "solid" },
		],
		[
			{ x: 6, y: 0, direction: "up" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 3, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
			{ x: 8, y: 0, direction: "up" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 8, y: 11, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 3, y: 11, direction: "down" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 5, direction: "right" },
			{ x: 0, y: 3, direction: "left" },
			{ x: 0, y: 4, direction: "left" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 0, y: 8, direction: "left" },
		],
		["up", "right"],
		["down"]
	),
	new Room(
		"gate-contraption",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 1, y: 9, type: "solid" },
			{ x: 1, y: 10, type: "solid" },
			{ x: 10, y: 9, type: "solid" },
			{ x: 10, y: 10, type: "solid" },
			{ x: 0, y: 3, type: "solid" },
			{ x: 0, y: 4, type: "solid" },
			{ x: 0, y: 5, type: "solid" },
			{ x: 0, y: 6, type: "solid" },
			{ x: 11, y: 6, type: "solid" },
			{ x: 11, y: 5, type: "solid" },
			{ x: 11, y: 4, type: "solid" },
			{ x: 11, y: 3, type: "solid" },
			{ x: 8, y: 0, type: "solid" },
			{ x: 7, y: 0, type: "solid" },
			{ x: 4, y: 9, type: "solid" },
			{ x: 5, y: 9, type: "solid" },
			{ x: 6, y: 9, type: "solid" },
			{ x: 7, y: 9, type: "solid" },
			{ x: 3, y: 9, type: "platform" },
			{ x: 2, y: 9, type: "platform" },
			{ x: 8, y: 9, type: "solid" },
			{ x: 8, y: 6, type: "solid" },
			{ x: 8, y: 7, type: new Gate("down", true) },
			{ x: 8, y: 8, type: new Gate("up", true) },
			{ x: 8, y: 3, type: "solid" },
			{ x: 8, y: 5, type: "solid" },
			{ x: 9, y: 5, type: "solid" },
			{ x: 8, y: 1, type: new Gate("down", false) },
			{ x: 8, y: 2, type: new Gate("up", false) },
			{ x: 10, y: 5, type: "solid" },
			{ x: 4, y: 2, type: "solid" },
			{ x: 3, y: 0, type: "solid" },
			{ x: 4, y: 0, type: "solid" },
			{ x: 4, y: 1, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 4, y: 4, type: "solid" },
			{ x: 4, y: 5, type: "solid" },
			{ x: 4, y: 6, type: "solid" },
			{ x: 2, y: 6, type: "solid" },
			{ x: 3, y: 6, type: "solid" },
			{ x: 1, y: 4, type: "solid" },
			{ x: 2, y: 4, type: "solid" },
			{ x: 2, y: 2, type: "solid" },
			{ x: 4, y: 8, type: new Gate("up", true) },
			{ x: 4, y: 7, type: new Gate("down", true) },
			{ x: 7, y: 6, type: "platform" },
			{ x: 6, y: 6, type: "platform" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 9, y: 3, type: "solid" },
			{ x: 2, y: 3, type: new Gate("down", false) },
		],
		[
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 8, y: 11, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
			{ x: 3, y: 11, direction: "down" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 6, y: 0, direction: "up" },
		],
		["left"],
		["right", "down"]
	),
	new Room(
		"the-tomb",
		[
			{ x: 0, y: 0, type: "solid" },
			{ x: 1, y: 0, type: "solid" },
			{ x: 2, y: 0, type: "solid" },
			{ x: 0, y: 1, type: "solid" },
			{ x: 0, y: 2, type: "solid" },
			{ x: 0, y: 9, type: "solid" },
			{ x: 0, y: 10, type: "solid" },
			{ x: 0, y: 11, type: "solid" },
			{ x: 1, y: 11, type: "solid" },
			{ x: 2, y: 11, type: "solid" },
			{ x: 9, y: 11, type: "solid" },
			{ x: 10, y: 11, type: "solid" },
			{ x: 11, y: 11, type: "solid" },
			{ x: 11, y: 10, type: "solid" },
			{ x: 11, y: 9, type: "solid" },
			{ x: 11, y: 2, type: "solid" },
			{ x: 11, y: 1, type: "solid" },
			{ x: 11, y: 0, type: "solid" },
			{ x: 10, y: 0, type: "solid" },
			{ x: 9, y: 0, type: "solid" },
			{ x: 8, y: 11, type: "solid" },
			{ x: 3, y: 11, type: "solid" },
			{ x: 1, y: 10, type: "solid" },
			{ x: 2, y: 10, type: "solid" },
			{ x: 8, y: 10, type: "solid" },
			{ x: 9, y: 10, type: "solid" },
			{ x: 10, y: 10, type: "solid" },
			{ x: 3, y: 10, type: "solid" },
			{ x: 3, y: 6, type: "solid" },
			{ x: 8, y: 6, type: "solid" },
			{ x: 7, y: 6, type: "solid" },
			{ x: 8, y: 7, type: "solid" },
			{ x: 4, y: 6, type: "solid" },
			{ x: 3, y: 7, type: "solid" },
			{ x: 3, y: 8, type: new Gate("down", true) },
			{ x: 3, y: 9, type: new Gate("up", true) },
			{ x: 8, y: 8, type: new Gate("down", true) },
			{ x: 8, y: 9, type: new Gate("up", true) },
			{ x: 6, y: 6, type: "platform" },
			{ x: 5, y: 6, type: "platform" },
			{ x: 7, y: 3, type: "solid" },
			{ x: 6, y: 3, type: "solid" },
			{ x: 5, y: 3, type: "solid" },
			{ x: 4, y: 3, type: "solid" },
			{ x: 0, y: 3, type: "solid" },
			{ x: 1, y: 3, type: "solid" },
			{ x: 11, y: 3, type: "solid" },
			{ x: 10, y: 3, type: "solid" },
			{ x: 11, y: 4, type: "solid" },
			{ x: 0, y: 4, type: "solid" },
			{ x: 9, y: 3, type: new Gate("left", false) },
			{ x: 8, y: 3, type: new Gate("right", false) },
			{ x: 2, y: 3, type: new Gate("right", false) },
			{ x: 3, y: 3, type: new Gate("left", false) },
			{ x: 7, y: 10, type: "platform" },
			{ x: 4, y: 10, type: "platform" },
		],
		[
			{ x: 6, y: 0, direction: "up" },
			{ x: 4, y: 0, direction: "up" },
			{ x: 3, y: 0, direction: "up" },
			{ x: 5, y: 0, direction: "up" },
			{ x: 7, y: 0, direction: "up" },
			{ x: 8, y: 0, direction: "up" },
			{ x: 11, y: 6, direction: "right" },
			{ x: 11, y: 7, direction: "right" },
			{ x: 11, y: 8, direction: "right" },
			{ x: 0, y: 8, direction: "left" },
			{ x: 0, y: 6, direction: "left" },
			{ x: 0, y: 7, direction: "left" },
			{ x: 11, y: 5, direction: "right" },
			{ x: 0, y: 5, direction: "left" },
			{ x: 4, y: 10, direction: "down" },
			{ x: 5, y: 10, direction: "down" },
			{ x: 6, y: 10, direction: "down" },
			{ x: 7, y: 10, direction: "down" },
			{ x: 7, y: 11, direction: "down" },
			{ x: 6, y: 11, direction: "down" },
			{ x: 5, y: 11, direction: "down" },
			{ x: 4, y: 11, direction: "down" },
		],
		["up", "left"],
		["down", "right"]
	)
];

for(const room of ROOMS) {
	ROOMS.push(room.reflect());
}
debugger;
