import { Vector } from "../../utils-ts/modules/geometry/Vector.mjs";
import { Portal } from "../entities/Portal.mjs";
import { WorldPart } from "../world-generator/WorldPart.mjs";
export let FLOOR_ZERO = new WorldPart();
export class FloorZeroData {
    static initialize() {
        FLOOR_ZERO = WorldPart.parse([
            { x: 11, y: 0, type: "solid" },
            { x: 11, y: 8, type: "solid" },
            { x: 11, y: 11, type: "solid" },
            { x: 10, y: 0, type: "solid" },
            { x: 10, y: 8, type: "solid" },
            { x: 10, y: 11, type: "solid" },
            { x: 9, y: 0, type: "solid" },
            { x: 9, y: 8, type: "solid" },
            { x: 9, y: 11, type: "solid" },
            { x: 2, y: 0, type: "solid" },
            { x: 2, y: 1, type: "solid" },
            { x: 2, y: 8, type: "solid" },
            { x: 2, y: 9, type: "solid" },
            { x: 2, y: 10, type: "solid" },
            { x: 2, y: 11, type: "solid" },
            { x: 1, y: 0, type: "solid" },
            { x: 1, y: 1, type: "solid" },
            { x: 1, y: 8, type: "solid" },
            { x: 1, y: 9, type: "solid" },
            { x: 1, y: 10, type: "solid" },
            { x: 1, y: 11, type: "solid" },
            { x: 0, y: 0, type: "solid" },
            { x: 0, y: 1, type: "solid" },
            { x: 0, y: 8, type: "solid" },
            { x: 0, y: 9, type: "solid" },
            { x: 0, y: 10, type: "solid" },
            { x: 0, y: 11, type: "solid" },
            { x: 3, y: 0, type: "solid" },
            { x: 5, y: 0, type: "solid" },
            { x: 7, y: 1, type: "solid" },
            { x: 10, y: 1, type: "solid" },
            { x: 12, y: 1, type: "solid" },
            { x: 13, y: 1, type: "solid" },
            { x: 14, y: 1, type: "solid" },
            { x: 12, y: 0, type: "solid" },
            { x: 9, y: 1, type: "solid" },
            { x: 8, y: 1, type: "solid" },
            { x: 6, y: 1, type: "solid" },
            { x: 6, y: 0, type: "solid" },
            { x: 7, y: 0, type: "solid" },
            { x: 8, y: 0, type: "solid" },
            { x: 4, y: 0, type: "solid" },
            { x: 3, y: 1, type: "solid" },
            { x: 4, y: 1, type: "solid" },
            { x: 5, y: 1, type: "solid" },
            { x: 13, y: 0, type: "solid" },
            { x: 14, y: 0, type: "solid" },
            { x: 15, y: 0, type: "solid" },
            { x: 16, y: 0, type: "solid" },
            { x: 11, y: 1, type: "solid" },
            { x: 16, y: 1, type: "solid" },
            { x: 17, y: 1, type: "solid" },
            { x: 18, y: 1, type: "solid" },
            { x: 17, y: 0, type: "solid" },
            { x: 18, y: 0, type: "solid" },
            { x: 19, y: 0, type: "solid" },
            { x: 19, y: 1, type: "solid" },
            { x: 15, y: 1, type: "solid" },
            { x: 20, y: 1, type: "solid" },
            { x: 20, y: 0, type: "solid" },
            { x: 21, y: 0, type: "solid" },
            { x: 22, y: 0, type: "solid" },
            { x: 23, y: 0, type: "solid" },
            { x: 23, y: 1, type: "solid" },
            { x: 22, y: 1, type: "solid" },
            { x: 21, y: 1, type: "solid" },
            { x: 3, y: 8, type: "solid" },
            { x: 4, y: 8, type: "solid" },
            { x: 5, y: 9, type: "solid" },
            { x: 4, y: 9, type: "solid" },
            { x: 3, y: 9, type: "solid" },
            { x: 3, y: 10, type: "solid" },
            { x: 4, y: 10, type: "solid" },
            { x: 5, y: 10, type: "solid" },
            { x: 6, y: 10, type: "solid" },
            { x: 7, y: 11, type: "solid" },
            { x: 6, y: 11, type: "solid" },
            { x: 5, y: 11, type: "solid" },
            { x: 4, y: 11, type: "solid" },
            { x: 3, y: 11, type: "solid" },
            { x: 16, y: 11, type: "solid" },
            { x: 15, y: 11, type: "solid" },
            { x: 14, y: 11, type: "solid" },
            { x: 13, y: 11, type: "solid" },
            { x: 12, y: 11, type: "solid" },
            { x: 12, y: 8, type: "solid" },
            { x: 13, y: 8, type: "solid" },
            { x: 14, y: 8, type: "solid" },
            { x: 18, y: 10, type: "solid" },
            { x: 15, y: 8, type: "solid" },
            { x: 17, y: 11, type: "solid" },
            { x: 18, y: 11, type: "solid" },
            { x: 19, y: 9, type: "solid" },
            { x: 19, y: 10, type: "solid" },
            { x: 20, y: 10, type: "solid" },
            { x: 20, y: 11, type: "solid" },
            { x: 19, y: 11, type: "solid" },
            { x: 20, y: 9, type: "solid" },
            { x: 20, y: 8, type: "solid" },
            { x: 21, y: 8, type: "solid" },
            { x: 21, y: 9, type: "solid" },
            { x: 21, y: 10, type: "solid" },
            { x: 22, y: 10, type: "solid" },
            { x: 22, y: 11, type: "solid" },
            { x: 21, y: 11, type: "solid" },
            { x: 22, y: 9, type: "solid" },
            { x: 23, y: 8, type: "solid" },
            { x: 23, y: 9, type: "solid" },
            { x: 23, y: 10, type: "solid" },
            { x: 23, y: 11, type: "solid" },
            { x: 22, y: 8, type: "solid" },
            { x: 8, y: 11, type: "solid" },
        ], [
            new Portal(new Vector(12 * 50, 8 * 50)),
        ]);
    }
}
//# sourceMappingURL=FloorZeroData.mjs.map