export const RENDERING_ORDER = [
    "backgrounds",
    "editor-background",
    "shake",
    "camera-translation",
    "glow",
    "player",
    "particle",
    "entity",
    "tile",
    "tile-accent",
    "tile-entity",
    "telegraph",
    "hitbox",
    "reset-shake",
    "reset-camera-translation",
    "overlay-text",
    "world-ui",
    "editor-ui",
    "start-screen-ui",
    "screen-fade",
    "debug-mouse-coordinates",
    "debug-fps",
];
//# sourceMappingURL=RenderingOrder.mjs.map